### ISSUE TITLE
FDR and track calculation error

### ISSUE THREAD

**Issue by mrvollger** [fiberseq/FIRE#13]
In calculating the FDR tracks (and peaks), fibers lacking any FIRE elements were not included in the FDR or coverage calculations. 

This is a substantial bug, and any analysis done with the FDR pipeline (Post Oct 15th 2023) should be repeated once I have a fix. 

Apologies to all.

**Comment by NurislamSheih** [comment]
Am I right that Fire v0.0.3 lacks that bug? If so, we will redo our analysis using v0.0.3.

**Comment by NurislamSheih** [comment]
Oh, I see the word post. I got it; the last version also has a bug.

**Comment by mrvollger** [comment]
fixed in 0.0.4 by #14.
