### ISSUE TITLE
Error message with latest FIRE: polars.exceptions.ComputeError: cannot sort column of dtype `null`

### ISSUE THREAD

**Issue by ywang285** [fiberseq/FIRE#16]
Hi @mrvollger, I am running FIRE on ONT Fiberseq data. I am using the 0.0.4 version of FIRE, and modified the env.yaml to let it use fibertools-rs=0.4.1 (somehow I cannot run fibertools-rs=0.4.2 because it will give "illegal instructions" message when I type "ft"). I got below error message:

[INFO][Time elapsed (ms) 28925]: Merging duplicates
/home/yw/.cache/snakemake/snakemake/source-cache/runtime-cache/tmpapm78p0w/file/home/yw/software/FIRE-0.0.4/workflow/rules/../scripts/fire-null-distribution.py:344: DeprecationWarning: `cumsum` is deprecated. It has been renamed to `cum_sum`.
  diff.cumsum().alias("group"),
/home/yw/.cache/snakemake/snakemake/source-cache/runtime-cache/tmpapm78p0w/file/home/yw/software/FIRE-0.0.4/workflow/rules/../scripts/fire-null-distribution.py:343: DeprecationWarning: `with_row_count` is deprecated. Use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df.with_columns(
/home/yw/.cache/snakemake/snakemake/source-cache/runtime-cache/tmpapm78p0w/file/home/yw/software/FIRE-0.0.4/workflow/rules/../scripts/fire-null-distribution.py:349: DeprecationWarning: `shift_and_fill` is deprecated. Use `shift` instead.
  pl.col("end").shift_and_fill(periods=1, fill_value=0).alias("start"),
/home/yw/.cache/snakemake/snakemake/source-cache/runtime-cache/tmpapm78p0w/file/home/yw/software/FIRE-0.0.4/workflow/rules/../scripts/fire-null-distribution.py:349: DeprecationWarning: `the argument periods` for `shift_and_fill` is deprecated. It has been renamed to `n`.
  pl.col("end").shift_and_fill(periods=1, fill_value=0).alias("start"),
Traceback (most recent call last):
  File "/home/yw/.cache/snakemake/snakemake/source-cache/runtime-cache/tmpapm78p0w/file/home/yw/software/FIRE-0.0.4/workflow/rules/../scripts/fire-null-distribution.py", line 565, in <module>
    defopt.run(main, show_types=True, version="0.0.1")
  File "/home/yw/software/snakemake-conda-envs/47cc8181788d779e36f05eceb982b9e1_/lib/python3.10/site-packages/defopt.py", line 356, in run
    return call()
  File "/home/yw/.cache/snakemake/snakemake/source-cache/runtime-cache/tmpapm78p0w/file/home/yw/software/FIRE-0.0.4/workflow/rules/../scripts/fire-null-distribution.py", line 560, in main
    write_scores(fire, fdr_table, outfile, min_coverage=min_coverage)
  File "/home/yw/.cache/snakemake/snakemake/source-cache/runtime-cache/tmpapm78p0w/file/home/yw/software/FIRE-0.0.4/workflow/rules/../scripts/fire-null-distribution.py", line 469, in write_scores
    write_bed(chrom, output_dict, outfile, first=first)
  File "/home/yw/.cache/snakemake/snakemake/source-cache/runtime-cache/tmpapm78p0w/file/home/yw/software/FIRE-0.0.4/workflow/rules/../scripts/fire-null-distribution.py", line 353, in write_bed
    .sort(["#chrom", "start", "end"])
  File "/home/yw/software/snakemake-conda-envs/47cc8181788d779e36f05eceb982b9e1_/lib/python3.10/site-packages/polars/dataframe/frame.py", line 4558, in sort
    self.lazy()
  File "/home/yw/software/snakemake-conda-envs/47cc8181788d779e36f05eceb982b9e1_/lib/python3.10/site-packages/polars/lazyframe/frame.py", line 1943, in collect
    return wrap_df(ldf.collect())
polars.exceptions.ComputeError: cannot sort column of dtype `null`
[Thu Apr 11 02:53:46 2024]
Error in rule fdr_track_chromosome:
    jobid: 27
    input: results/dml_cc_ec/fiber-calls/FIRE.bed.gz, results/dml_cc_ec/fiber-calls/FIRE.bed.gz.tbi, results/dml_cc_ec/coverage/fiber-locations.bed.gz, /home/yw/Genome/hg38.analysisSet.fa.fai, results/dml_cc_ec/FDR-peaks/FIRE.score.to.FDR.tbl
    output: temp/dml_cc_ec/FDR-peaks/chr7-fire.bed, temp/dml_cc_ec/FDR-peaks/chr7-fiber.bed, temp/dml_cc_ec/FDR-peaks/chr7-FDR.track.bed
    conda-env: /home/yw/software/snakemake-conda-envs/47cc8181788d779e36f05eceb982b9e1_
    shell:
        
        tabix -h results/dml_cc_ec/fiber-calls/FIRE.bed.gz chr7 > temp/dml_cc_ec/FDR-peaks/chr7-fire.bed
        tabix -h results/dml_cc_ec/coverage/fiber-locations.bed.gz chr7 > temp/dml_cc_ec/FDR-peaks/chr7-fiber.bed

        # check if file is empty
        if [ ! -s temp/dml_cc_ec/FDR-peaks/chr7-fire.bed ]; then
            echo "No FIRE sites for chr7"
            touch temp/dml_cc_ec/FDR-peaks/chr7-fire.bed temp/dml_cc_ec/FDR-peaks/chr7-fiber.bed temp/dml_cc_ec/FDR-peaks/chr7-FDR.track.bed
            exit 0
        fi

        python /home/yw/.cache/snakemake/snakemake/source-cache/runtime-cache/tmpapm78p0w/file/home/yw/software/FIRE-0.0.4/workflow/rules/../scripts/fire-null-distribution.py -v 1             temp/dml_cc_ec/FDR-peaks/chr7-fire.bed temp/dml_cc_ec/FDR-peaks/chr7-fiber.bed             /home/yw/Genome/hg38.analysisSet.fa.fai -f results/dml_cc_ec/FDR-peaks/FIRE.score.to.FDR.tbl             -o temp/dml_cc_ec/FDR-peaks/chr7-FDR.track.bed
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job fdr_track_chromosome since they might be corrupted:
temp/dml_cc_ec/FDR-peaks/chr7-fire.bed, temp/dml_cc_ec/FDR-peaks/chr7-fiber.bed
[Thu Apr 11 02:54:14 2024]
Finished job 17.
35 of 58 steps (60%) done
Removing temporary output temp/dml_cc_ec/coverage/all/linker_chr7.bed.gz.
Removing temporary output temp/dml_cc_ec/coverage/all/nucleosome_chr7.bed.gz.
Removing temporary output temp/dml_cc_ec/coverage/all/fire_chr7.bed.gz.
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-04-11T025042.702967.snakemake.log
WorkflowError:
At least one job did not complete successfully.

Do you have any idea about how to fix this issue? Thank you so much!

**Comment by mrvollger** [comment]
Can you try pulling the latest version of the code? I think this has to do with a version issue I previously fixed:
<img width="1459" alt="image" src="https://github.com/fiberseq/FIRE/assets/6935283/c65cf69c-9814-4133-9aea-4a50473f369a">

**Comment by ywang285** [comment]
Thank you so much @mrvollger ! I pulled the Targeted #15 version and the code did run through without an error. In fact I am doing both targeted FIberseq as well as whole genome Fiberseq. Does this "Targeted" version of code works for both cases?

**Comment by mrvollger** [comment]
I merged this fix into main. Currently processing targeted data is still just a goal and not actually coded up either in main or the branch. So unfortunately I don't have a recommendation for that at this time.
