### ISSUE TITLE
bad links

### ISSUE THREAD

**Issue by kerrybubb** [fiberseq/FIRE#19]
The "configuration README" and "configuration file" and "manifest file" links under "Configuring" on the main page (https://github.com/fiberseq/FIRE?tab=readme-ov-file) have typos in the urls. For example, if you click on "configuration README" it goes to:

https://github.com/fiberseq/FIRE/blob/main/%60config/README.md%60

instead of 

https://github.com/fiberseq/FIRE/blob/main/config/README.md

Similar issue with the other two links.

**Comment by mrvollger** [comment]
Fixed in ab3c365664b261b1492af53a6deb0f980bb1535c
