### ISSUE TITLE
Typo for installing snakemake executor plugin

### ISSUE THREAD

**Issue by tbenavi1** [fiberseq/FIRE#20]
Hello, I believe there is a typo in the readme file for installing the snakemake executor plugin. The correct command should be:
```
pip install snakemake-executor-plugin-cluster-generic
```

I think there were a few places in the snakemake github/website where they had incorrectly stated the name of the plugin.

**Comment by mrvollger** [comment]
There are multiple valid plugins for executing. I use slurm as an example, and the one you have linked is another valid example. I have the snakemake docs linked to encourage people to find what works for their HPC but if you have a different language recommendation I'd consider it.
