### ISSUE TITLE
FIRE element size distribution

### ISSUE THREAD

**Issue by ywang285** [fiberseq/FIRE#21]
Hi, I am working on ONT Fiberseq data and I plotted the FIRE element size distribution. Please see figure attached below. The orange histogram represents FIRE element size distribution and blue histogram represents MSP size distribution. I found there are two peaks in the orange histogram -- a small peak centered around 100bp and a much larger peak with long tail. I wonder why that is the case (i.e., two length population for FIRE elements)? Thank you in advance!

![image](https://github.com/fiberseq/FIRE/assets/34822355/c156465d-22b1-40b6-90a1-8c14aec975c0)

**Comment by mrvollger** [comment]
If MSP length was a perfect discriminator of accessible chromatin we wouldn't need FIRE at all. But it's not so we do this extra work to better infer these regions. 

Re your specific ONT data I have no idea, but it wouldn't be hard for you to see if these smaller elements are enriched for certain mapping locations. 

Also, as always I need to note, glad ONT seems to work for you but it is not yet supported so take results with a grain of salt.
