### ISSUE TITLE
Output model.results.bed.gz

### ISSUE THREAD

**Issue by ywang285** [fiberseq/FIRE#24]
Hi, I am hoping to obtain positions of all linker elements (excluding FIRE elements). I am wondering if there is a way to output the model.results.bed.gz that includes Every FIRE, linker, and nucleosome in every fiber (It seems that the bed file was included in the 'fiber-calls' folder in an earlier version of FIRE but not in current version)? Thank you!

**Comment by StephanieBohaczuk** [comment]
I think you might be looking for this (copied from a note written by @mrvollger on slack).

 using the fire.bam created by the pipeline you can do
 `ft fire -t 8 --extract fire.bam > all.bed`
or for a rgn
 `samtools view -@ 8 -u fire.bam myrgn:1-1000 | ft fire -t 8 --extract fire.bam > rgn.bed`

**Comment by mrvollger** [comment]
Yep that's right @StephanieBohaczuk!

**Comment by ywang285** [comment]
Thank you so much @StephanieBohaczuk and @mrvollger!
