### ISSUE TITLE
Issues with new update

### ISSUE THREAD

**Issue by dverac** [fiberseq/FIRE#25]
Hi!

I am trying to run FIRE, but I am running on some errors with the new version.  I tried both with ./fire executable, or with snakemake itself, in both cases, my profile yaml is similar, just adjusting account and partition in slurm, but I get the same error.

**snakemake: error: unrecognized arguments: --software-deployment-method=apptainer --software-deployment-method=conda --executor=slurm**

I am running it using Snakemake version 7.32.4. I suspect I should be trying using a different Snakemake version.

**Comment by mrvollger** [comment]
Yep, you need snakemake 8.4 or greater:
https://github.com/fiberseq/FIRE?tab=readme-ov-file#install
8.0, unfortunately, has breaking CLI changes.
