### ISSUE TITLE
seed option for 'bedtools shuffle' in FDR-peaks.smk

### ISSUE THREAD

**Issue by RisaWatanabe** [fiberseq/FIRE#26]
Hi,

Thank you so much for creating such a wonderful bioinformatic tool.
I ran FIRE (v0.06) on the same bam file (hiphase output)  twice with exactly the same environment/script, and the number of FDR-FIRE peaks (FDR-FIRE-peaks.bed.gz) were slightly different (57,972 vs 57,337).  We noticed that the rule 'filtered_and_shuffled_fiber_locations_chromosome' in 'FDR-peaks.smk' uses 'bedtools shuffle' to create the background shuffled fiber. 

Bedtools shuffle uses a pseudo-random number generator to permute the locations of BED features. Bedtools shuffle has an option '-seed' which supplies a custom integer seed for bedtools shuffle. If we use this seed option, each execution of bedtools shuffle with the same seed and the same input file should produce identical results.
https://bedtools.readthedocs.io/en/latest/content/tools/shuffle.html

Is it possible that you add '-seed' option to your bedtools shuffle so that we could produce identical results for an input file?

Thank you!

**Comment by mrvollger** [comment]
We could add the seed option there but there are many other steps in the pipeline that I believe to be non deterministic. 

I think it would be better for me to just document that it is not deterministic. 

Unless you are saying that you tried the seed option for bedtools and it gave deterministic output for the whole pipeline?

**Comment by RisaWatanabe** [comment]
I did not try the seed option for bedtools shuffle in your FIRE.
The two runs had the same number of rows for FIRE.bed.gz, just a slight difference in the number of FDR-FIRE peaks. 
(I actually have a third run, which used FIRE_v0.04, that also resulted in a same # of FIREs but slightly different # of FDR-FIREs as the other two runs.)
This made me assume that your FIRE pipeline is pretty deterministic except for the FDR-FIRE identification that uses 'bedtools shuffle'.
