### ISSUE TITLE
Different #peaks in 'peaks-vs-percent.pdf'

### ISSUE THREAD

**Issue by RisaWatanabe** [fiberseq/FIRE#28]
When we run FIRE_v0.06, we noticed different peak counts displayed in the 'FDR-peaks/peaks-vs-percent.pdf' that do not match one another and also do not match FDR-FIRE.bed.gz. The numbers are usually very close to one another, as in the example below. I assume this is due to some rows dropping out in 'peaks-vs-percent.R.' 
I am running FIRE in a conda environment with snakemake_v8.10.6 and mamba_v1.5.8.

Please refer below for one example of 'peaks-vs-percent.pdf'. 'wc -l' for this sample's FDR-FIRE-peaks.bed.gz was 58.041.
![peaks-vs-percent](https://github.com/fiberseq/FIRE/assets/21050912/1f0f6270-466c-4eea-9cdd-bb744f1a5bdc)

Thank you!

**Comment by mrvollger** [comment]
The discrepancy between the plot and the file is expected since the peak file includes peaks that fail the coverage filter. 

However, the discrepancy within the plot is not expected and not something I have seen before. 

I'd be happy to take a look if you can share just the peak file.

**Comment by mrvollger** [comment]
This is a small bug in the top histogram. The bottom part is the correct one. 

Will be fixed in the next release.

**Comment by RisaWatanabe** [comment]
Thank you Mitchell! I look forward to the next release.
