### ISSUE TITLE
error with the Snakemake

### ISSUE THREAD

**Issue by bshrestha617** [fiberseq/FIRE#31]
Hi,
I am trying to use FIRE pipeline to execute the ONT data but I am getting the following error:

TypeError in file /FIRE/workflow/Snakefile, line 10:
expected string or bytes-like object, got 'dict

**Comment by mrvollger** [comment]
I believe you have run into a bug with conda inject that was fixed in this release:
https://github.com/koesterlab/conda-inject/releases/tag/v1.3.2
Please try updating to this version of conda inject within your snakemake python environment and see if that helps.
