### ISSUE TITLE
Order of phasing and fibertools

### ISSUE THREAD

**Issue by tbenavi1** [fiberseq/FIRE#5]
Hello,

Is there a preferred order for phasing the reads and running fibertools? Or does it matter? In other words is the pipeline:

1) phasing, fibertools, FIRE
2) fibertools, phasing, FIRE

Thank you for any insight.

**Comment by sjneph** [comment]
ft predict-m6a then phasing then FIRE.

**Comment by tbenavi1** [comment]
Thank you.
