### ISSUE TITLE
Questions about FIRE and ft add-nucleosomes

### ISSUE THREAD

**Issue by ywang285** [fiberseq/FIRE#9]
Hi, thank you for sharing this great FIRE pipeline. I have been using FIRE to call actuated regulatory elements with nanopore data. Can I ask some questions about FIRE and fibertools-rs: 
1. For each read, are linker regions and FIRE regions and nucleosome regions cover the entire read? For example, if I want to calculate nucleosome occupancy at each base pair across the genome, can I just use the information in "FIRE_results/coverage/all_element_coverages.bed.gz", and calculate nuc/(FIRE+linker+nuc)? How does ft add-nuclesomes deal with a region that is large (like 1000bp) but does not have any 6mA modifications? Will it add 5 nucleosomes to the region or just 1 nucleosome with 1000bp length?
2. If I want to study co-actuation of regulatory elements on each read, is there an easy way to fetch desired reads within a region (like the fiberbam.fetch() in pyft) and extract start/end coordinates for each FIRE region on every fetched reads?
Thank you!

**Comment by mrvollger** [comment]
> For each read, are linker regions and FIRE regions and nucleosome regions cover the entire read?

basically, yes, the first couple and last ~45 bp of reads are uncalled though.

> For example, if I want to calculate nucleosome occupancy at each base pair across the genome, can I just use the information in "FIRE_results/coverage/all_element_coverages.bed.gz", and calculate nuc/(FIRE+linker+nuc)?

yes

> How does ft add-nuclesomes deal with a region that is large (like 1000bp) but does not have any 6mA modifications? Will it add 5 nucleosomes to the region or just 1 nucleosome with 1000bp length?

One nucleosome, though there are few to zero regions in the human genome without any ATs in 1000bp. 

> If I want to study co-actuation of regulatory elements on each read, is there an easy way to fetch desired reads within a region (like the fiberbam.fetch() in pyft) and extract start/end coordinates for each FIRE region on every fetched reads?

See `FIRE.bed.gz` on this page, https://github.com/fiberseq/FIRE/tree/main/docs, and then you can quickly and easily extract subregions from this bed with `tabix`. e.g. `tabix FIRE.bed.gz chr1:1-1000`

**Comment by ywang285** [comment]
Thank you so much for your reply! Where can I find description for each column in FIRE.bed.gz, fire-fibers.bed.gz, and fire-fiber-decorators.bed.gz?
